elasticsearch:
  host: 192.168.13.46
  port: 9200


# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/Agoods?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.itheima.elasticsearchdemo2.domain

